# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: join_order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='join_order.proto',
  package='join_order',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001Z$github.com/pingcap/tidb/planner/core',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10join_order.proto\x12\njoin_order\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xb5\x01\n\x0fLogicalJoinNode\x12\n\n\x02tp\x18\x01 \x01(\t\x12.\n\tchildrens\x18\x02 \x03(\x0b\x32\x1b.join_order.LogicalJoinNode\x12\x39\n\nconditions\x18\x03 \x03(\x0b\x32%.join_order.LogicalJoinNode.Condition\x1a+\n\tCondition\x12\x10\n\x08\x66uncname\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"m\n\x05State\x12\x36\n\x11\x63urrent_join_tree\x18\x01 \x01(\x0b\x32\x1b.join_order.LogicalJoinNode\x12,\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x1b.join_order.LogicalJoinNode2\x8e\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x18.join_order.HelloRequest\x1a\x16.join_order.HelloReply\"\x00\x12\x43\n\rSayHelloAgain\x12\x18.join_order.HelloRequest\x1a\x16.join_order.HelloReply\"\x00\x32\x8c\x01\n\tJoinOrder\x12\x45\n\x0cTestJoinNode\x12\x1b.join_order.LogicalJoinNode\x1a\x16.join_order.HelloReply\"\x00\x12\x38\n\tGetAction\x12\x11.join_order.State\x1a\x16.join_order.HelloReply\"\x00\x42V\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z$github.com/pingcap/tidb/planner/coreb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='join_order.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='join_order.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='join_order.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='join_order.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_LOGICALJOINNODE_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='join_order.LogicalJoinNode.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='funcname', full_name='join_order.LogicalJoinNode.Condition.funcname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='join_order.LogicalJoinNode.Condition.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=275,
)

_LOGICALJOINNODE = _descriptor.Descriptor(
  name='LogicalJoinNode',
  full_name='join_order.LogicalJoinNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tp', full_name='join_order.LogicalJoinNode.tp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='childrens', full_name='join_order.LogicalJoinNode.childrens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='join_order.LogicalJoinNode.conditions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOGICALJOINNODE_CONDITION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=275,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='join_order.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_join_tree', full_name='join_order.State.current_join_tree', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='join_order.State.actions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=386,
)

_LOGICALJOINNODE_CONDITION.containing_type = _LOGICALJOINNODE
_LOGICALJOINNODE.fields_by_name['childrens'].message_type = _LOGICALJOINNODE
_LOGICALJOINNODE.fields_by_name['conditions'].message_type = _LOGICALJOINNODE_CONDITION
_STATE.fields_by_name['current_join_tree'].message_type = _LOGICALJOINNODE
_STATE.fields_by_name['actions'].message_type = _LOGICALJOINNODE
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['LogicalJoinNode'] = _LOGICALJOINNODE
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'join_order_pb2'
  # @@protoc_insertion_point(class_scope:join_order.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'join_order_pb2'
  # @@protoc_insertion_point(class_scope:join_order.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

LogicalJoinNode = _reflection.GeneratedProtocolMessageType('LogicalJoinNode', (_message.Message,), {

  'Condition' : _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {
    'DESCRIPTOR' : _LOGICALJOINNODE_CONDITION,
    '__module__' : 'join_order_pb2'
    # @@protoc_insertion_point(class_scope:join_order.LogicalJoinNode.Condition)
    })
  ,
  'DESCRIPTOR' : _LOGICALJOINNODE,
  '__module__' : 'join_order_pb2'
  # @@protoc_insertion_point(class_scope:join_order.LogicalJoinNode)
  })
_sym_db.RegisterMessage(LogicalJoinNode)
_sym_db.RegisterMessage(LogicalJoinNode.Condition)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'join_order_pb2'
  # @@protoc_insertion_point(class_scope:join_order.State)
  })
_sym_db.RegisterMessage(State)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='join_order.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=389,
  serialized_end=531,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='join_order.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='join_order.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER


_JOINORDER = _descriptor.ServiceDescriptor(
  name='JoinOrder',
  full_name='join_order.JoinOrder',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=534,
  serialized_end=674,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestJoinNode',
    full_name='join_order.JoinOrder.TestJoinNode',
    index=0,
    containing_service=None,
    input_type=_LOGICALJOINNODE,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAction',
    full_name='join_order.JoinOrder.GetAction',
    index=1,
    containing_service=None,
    input_type=_STATE,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOINORDER)

DESCRIPTOR.services_by_name['JoinOrder'] = _JOINORDER

# @@protoc_insertion_point(module_scope)
